spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver

eureka.client.service-url.defaultZone=https://localhost:8761/eureka/
eureka.instance.hostname=localhost

jwt.secret=MySuperSecretKeyForJWTGenerationAndValidation
